allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@next/env@16.3.8"
  - "@next/eslint-plugin-next@16.3.8"
  - "@next/swc-darwin-arm64@16.3.8"
  - "@next/swc-darwin-x64@16.3.8"
  - "@next/swc-linux-arm64-gnu@16.3.8"
  - "@next/swc-linux-arm64-musl@16.3.8"
  - "@next/swc-linux-x64-gnu@16.3.8"
  - "@next/swc-linux-x64-musl@16.3.8"
  - "@next/swc-win32-arm64-msvc@16.3.8"
  - "@next/swc-win32-x64-msvc@16.3.8"
  - "@vitest/mocker@5.0.3"
  - "@vitest/spy@5.0.3"
  - next@16.3.8
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
  - vitest@5.0.3
